version: 2
updates:
  - package-ecosystem: "python"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    assignee: webersni

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    assignee: webersni

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    assignee: webersni
