version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: 
      - "webersni"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees: 
      - "webersni"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "webersni"
