# Generated by Django 3.0.8 on 2020-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECBRiskFreeRate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateUSDPerX',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EUR', models.DecimalField(decimal_places=8, max_digits=10)),
                ('JPY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('GBP', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CHF', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RUB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AUD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BRL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CAD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CNY', models.DecimalField(decimal_places=2, max_digits=10)),
                ('INR', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FiveFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('RMW', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CMA', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ThreeFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10)),
                ('MktRF', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
