# Generated by Django 3.0.8 on 2020-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuallyECBRiskFreeRate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='AnnuallyExchangeRateUSDPerX',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EUR', models.DecimalField(decimal_places=8, max_digits=10)),
                ('JPY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('GBP', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CHF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RUB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('AUD', models.DecimalField(decimal_places=8, max_digits=10)),
                ('BRL', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CAD', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CNY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('INR', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='AnnuallyFiveFactor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MktRF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RMW', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CMA', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DailyECBRiskFreeRate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DailyExchangeRateUSDPerX',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EUR', models.DecimalField(decimal_places=8, max_digits=10)),
                ('JPY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('GBP', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CHF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RUB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('AUD', models.DecimalField(decimal_places=8, max_digits=10)),
                ('BRL', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CAD', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CNY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('INR', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DailyFiveFactor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MktRF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RMW', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CMA', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DailyThreeFactor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MktRF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyECBRiskFreeRate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyExchangeRateUSDPerX',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EUR', models.DecimalField(decimal_places=8, max_digits=10)),
                ('JPY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('GBP', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CHF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RUB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('AUD', models.DecimalField(decimal_places=8, max_digits=10)),
                ('BRL', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CAD', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CNY', models.DecimalField(decimal_places=8, max_digits=10)),
                ('INR', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyFiveFactor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MktRF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RMW', models.DecimalField(decimal_places=8, max_digits=10)),
                ('CMA', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyThreeFactor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MktRF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='YearlyThreeFactor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MktRF', models.DecimalField(decimal_places=8, max_digits=10)),
                ('SMB', models.DecimalField(decimal_places=8, max_digits=10)),
                ('HML', models.DecimalField(decimal_places=8, max_digits=10)),
                ('RF', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
